"""Add game table

Revision ID: 0556a4f8a1c6
Revises: 5a53ab9614d9
Create Date: 2023-08-29 01:01:57.167806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0556a4f8a1c6'
down_revision: Union[str, None] = '5a53ab9614d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('game_difficulty', sa.String(), nullable=True),
    sa.Column('game_outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
